### ISSUE TITLE
Deployment On vercel

### ISSUE THREAD

**Issue by SirdLay** [jonn-L/pastebin#1]
Hey, Hope you're doing good.
I deployed this app on vercel but I received application error. Could you provide any guidelines ? 

I added my MYSQL server url in env variable of vercel as : DATABASE_URL
also added VERCEL_URL too
The thing is when I save a paste it generates url but then shows application error

**Comment by SirdLay** [comment]
bump .

`SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4747:19)
    at successSteps (node:internal/deps/undici/undici:4718:27)
    at fullyReadBody (node:internal/deps/undici/undici:1433:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:4727:7)
    at async getText (/var/task/.next/server/app/[paste]/page.js:1:1879)
    at async NewPaste (/var/task/.next/server/app/[paste]/page.js:1:2055)`

`[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '672921896'
}`
